name: Publish Docker image

on:
  push:
    branches:
      - master
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
  
      # checkout
#       - name: Check out the repo
#         uses: actions/checkout@v2
      
#       # build
#       - name: Build the Docker image
#         run: docker build . --file Dockerfile --tag kevin031/blog-nextjs:latest

#       # login
#       - name: Log in to Docker Hub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

#       # push to docker hub
#       - name: Push to Docker Hub
#         uses: docker/build-push-action@v2
#         with:
#           push: true
#           tags: kevin031/blog-nextjs:latest

      - name: Execute SSH commmands on remote server
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: '122.51.210.138'
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
          debug: true
          command: |
            docker rm -f kevinlau-cn
            docker pull kevin031/blog-nextjs
            docker run --name kevinlau-cn --restart unless-stopped -p 20350:3000 -d kevin031/blog-nextjs
            
            
